name: page-build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.2.0
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}